//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.19 at 04:53:25 PM PST 
//


package com.itafin.addressvalidation.express;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.itafin.addressvalidation.util.MDStatus;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ErrorString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Results">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Result" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CityAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CityNotAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CountrySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AddressKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SuiteCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SuiteList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="PlusFour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="MAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="BaseMAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "resultCode",
    "errorString",
    "results"
})
@XmlRootElement(name = "Response")
public class ExpressResponse {

    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "ResultCode", required = true)
    protected String resultCode;
    @XmlElement(name = "ErrorString", required = true)
    protected String errorString;
    @XmlElement(name = "Results", required = true)
    protected ExpressResponse.Results results;
    
    @XmlTransient
    private MDStatus status = new MDStatus();
    
	public boolean isSuccess() {
		return status.isAddressSearchSuccess();
	}

	public void setResultStatus(String resultCode) {
		status.setResultCode(resultCode);
	}

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the errorString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorString() {
        return errorString;
    }

    /**
     * Sets the value of the errorString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorString(String value) {
        this.errorString = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressResponse.Results }
     *     
     */
    public ExpressResponse.Results getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressResponse.Results }
     *     
     */
    public void setResults(ExpressResponse.Results value) {
        this.results = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Result" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CityAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CityNotAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CountrySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="AddressKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SuiteCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SuiteList" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="PlusFour" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="MAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="BaseMAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result"
    })
    public static class Results {

        @XmlElement(name = "Result", required = true)
        protected List<ExpressResponse.Results.Result> result;

        /**
         * Gets the value of the result property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the result property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExpressResponse.Results.Result }
         * 
         * 
         */
        public List<ExpressResponse.Results.Result> getResult() {
            if (result == null) {
                result = new ArrayList<ExpressResponse.Results.Result>();
            }
            return this.result;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CityAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CityNotAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CountrySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="AddressKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SuiteCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SuiteList" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="PlusFour" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="MAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="BaseMAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address"
        })
        public static class Result {

            @XmlElement(name = "Address", required = true)
            protected ExpressResponse.Results.Result.Address address;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link ExpressResponse.Results.Result.Address }
             *     
             */
            public ExpressResponse.Results.Result.Address getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link ExpressResponse.Results.Result.Address }
             *     
             */
            public void setAddress(ExpressResponse.Results.Result.Address value) {
                this.address = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CityAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CityNotAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CountrySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="AddressKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SuiteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SuiteCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SuiteList" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="PlusFour" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="MAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="BaseMAK" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "addressLine1",
                "city",
                "cityAccepted",
                "cityNotAccepted",
                "state",
                "postalCode",
                "countrySubdivisionCode",
                "addressKey",
                "suiteName",
                "suiteCount",
                "suiteList",
                "plusFour",
                "mak",
                "baseMAK"
            })
            public static class Address {

                @XmlElement(name = "AddressLine1", required = true)
                protected String addressLine1;
                @XmlElement(name = "City", required = true)
                protected String city;
                @XmlElement(name = "CityAccepted", required = true)
                protected String cityAccepted;
                @XmlElement(name = "CityNotAccepted", required = true)
                protected String cityNotAccepted;
                @XmlElement(name = "State", required = true)
                protected String state;
                @XmlElement(name = "PostalCode", required = true)
                protected String postalCode;
                @XmlElement(name = "CountrySubdivisionCode", required = true)
                protected String countrySubdivisionCode;
                @XmlElement(name = "AddressKey", required = true)
                protected String addressKey;
                @XmlElement(name = "SuiteName", required = true)
                protected String suiteName;
                @XmlElement(name = "SuiteCount", required = true)
                protected String suiteCount;
                @XmlElement(name = "SuiteList", required = true)
                protected String suiteList;
                @XmlElement(name = "PlusFour", required = true)
                protected String plusFour;
                @XmlElement(name = "MAK", required = true)
                protected String mak;
                @XmlElement(name = "BaseMAK", required = true)
                protected String baseMAK;

                /**
                 * Gets the value of the addressLine1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressLine1() {
                    return addressLine1;
                }

                /**
                 * Sets the value of the addressLine1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressLine1(String value) {
                    this.addressLine1 = value;
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the cityAccepted property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCityAccepted() {
                    return cityAccepted;
                }

                /**
                 * Sets the value of the cityAccepted property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCityAccepted(String value) {
                    this.cityAccepted = value;
                }

                /**
                 * Gets the value of the cityNotAccepted property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCityNotAccepted() {
                    return cityNotAccepted;
                }

                /**
                 * Sets the value of the cityNotAccepted property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCityNotAccepted(String value) {
                    this.cityNotAccepted = value;
                }

                /**
                 * Gets the value of the state property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getState() {
                    return state;
                }

                /**
                 * Sets the value of the state property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setState(String value) {
                    this.state = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPostalCode(String value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the countrySubdivisionCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountrySubdivisionCode() {
                    return countrySubdivisionCode;
                }

                /**
                 * Sets the value of the countrySubdivisionCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountrySubdivisionCode(String value) {
                    this.countrySubdivisionCode = value;
                }

                /**
                 * Gets the value of the addressKey property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressKey() {
                    return addressKey;
                }

                /**
                 * Sets the value of the addressKey property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressKey(String value) {
                    this.addressKey = value;
                }

                /**
                 * Gets the value of the suiteName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuiteName() {
                    return suiteName;
                }

                /**
                 * Sets the value of the suiteName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuiteName(String value) {
                    this.suiteName = value;
                }

                /**
                 * Gets the value of the suiteCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuiteCount() {
                    return suiteCount;
                }

                /**
                 * Sets the value of the suiteCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuiteCount(String value) {
                    this.suiteCount = value;
                }

                /**
                 * Gets the value of the suiteList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuiteList() {
                    return suiteList;
                }

                /**
                 * Sets the value of the suiteList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuiteList(String value) {
                    this.suiteList = value;
                }

                /**
                 * Gets the value of the plusFour property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPlusFour() {
                    return plusFour;
                }

                /**
                 * Sets the value of the plusFour property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPlusFour(String value) {
                    this.plusFour = value;
                }

                /**
                 * Gets the value of the mak property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMAK() {
                    return mak;
                }

                /**
                 * Sets the value of the mak property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMAK(String value) {
                    this.mak = value;
                }

                /**
                 * Gets the value of the baseMAK property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBaseMAK() {
                    return baseMAK;
                }

                /**
                 * Sets the value of the baseMAK property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBaseMAK(String value) {
                    this.baseMAK = value;
                }

            }

        }

    }

}
