//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.17 at 10:32:22 AM PST 
//


package com.itafin.boe.geo.response.multimatch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locations" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="addressName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="street_1">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="zip_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="community_planning_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="coords">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="geocoding_source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "locations",
    "geocodingSource"
})
@XmlRootElement(name = "Address-Response")
public class AddressResponse {

    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected List<AddressResponse.Locations> locations;
    @XmlElement(name = "geocoding_source", required = true)
    protected String geocodingSource;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressResponse.Locations }
     * 
     * 
     */
    public List<AddressResponse.Locations> getLocations() {
        if (locations == null) {
            locations = new ArrayList<AddressResponse.Locations>();
        }
        return this.locations;
    }

    /**
     * Gets the value of the geocodingSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeocodingSource() {
        return geocodingSource;
    }

    /**
     * Sets the value of the geocodingSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeocodingSource(String value) {
        this.geocodingSource = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="addressName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="street_1">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="zip_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="community_planning_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="coords">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location"
    })
    public static class Locations {

        @XmlElement(required = true)
        protected AddressResponse.Locations.Location location;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link AddressResponse.Locations.Location }
         *     
         */
        public AddressResponse.Locations.Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressResponse.Locations.Location }
         *     
         */
        public void setLocation(AddressResponse.Locations.Location value) {
            this.location = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="addressName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="street_1">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="zip_code" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="community_planning_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="score" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="coords">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressName",
            "street1",
            "zipCode",
            "communityPlanningArea",
            "score",
            "coords"
        })
        public static class Location {

            @XmlElement(required = true)
            protected String addressName;
            @XmlElement(name = "street_1", required = true)
            protected AddressResponse.Locations.Location.Street1 street1;
            @XmlElement(name = "zip_code")
            protected int zipCode;
            @XmlElement(name = "community_planning_area", required = true)
            protected String communityPlanningArea;
            protected int score;
            @XmlElement(required = true)
            protected AddressResponse.Locations.Location.Coords coords;

            /**
             * Gets the value of the addressName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressName() {
                return addressName;
            }

            /**
             * Sets the value of the addressName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressName(String value) {
                this.addressName = value;
            }

            /**
             * Gets the value of the street1 property.
             * 
             * @return
             *     possible object is
             *     {@link AddressResponse.Locations.Location.Street1 }
             *     
             */
            public AddressResponse.Locations.Location.Street1 getStreet1() {
                return street1;
            }

            /**
             * Sets the value of the street1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link AddressResponse.Locations.Location.Street1 }
             *     
             */
            public void setStreet1(AddressResponse.Locations.Location.Street1 value) {
                this.street1 = value;
            }

            /**
             * Gets the value of the zipCode property.
             * 
             */
            public int getZipCode() {
                return zipCode;
            }

            /**
             * Sets the value of the zipCode property.
             * 
             */
            public void setZipCode(int value) {
                this.zipCode = value;
            }

            /**
             * Gets the value of the communityPlanningArea property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCommunityPlanningArea() {
                return communityPlanningArea;
            }

            /**
             * Sets the value of the communityPlanningArea property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCommunityPlanningArea(String value) {
                this.communityPlanningArea = value;
            }

            /**
             * Gets the value of the score property.
             * 
             */
            public int getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             * 
             */
            public void setScore(int value) {
                this.score = value;
            }

            /**
             * Gets the value of the coords property.
             * 
             * @return
             *     possible object is
             *     {@link AddressResponse.Locations.Location.Coords }
             *     
             */
            public AddressResponse.Locations.Location.Coords getCoords() {
                return coords;
            }

            /**
             * Sets the value of the coords property.
             * 
             * @param value
             *     allowed object is
             *     {@link AddressResponse.Locations.Location.Coords }
             *     
             */
            public void setCoords(AddressResponse.Locations.Location.Coords value) {
                this.coords = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "x",
                "y",
                "longitude",
                "latitude"
            })
            public static class Coords {

                protected double x;
                protected double y;
                protected double longitude;
                protected double latitude;

                /**
                 * Gets the value of the x property.
                 * 
                 */
                public double getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 */
                public void setX(double value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 */
                public double getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 */
                public void setY(double value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the longitude property.
                 * 
                 */
                public double getLongitude() {
                    return longitude;
                }

                /**
                 * Sets the value of the longitude property.
                 * 
                 */
                public void setLongitude(double value) {
                    this.longitude = value;
                }

                /**
                 * Gets the value of the latitude property.
                 * 
                 */
                public double getLatitude() {
                    return latitude;
                }

                /**
                 * Sets the value of the latitude property.
                 * 
                 */
                public void setLatitude(double value) {
                    this.latitude = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "houseNumber",
                "fraction",
                "direction",
                "streetName",
                "suffix",
                "suffixDir",
                "zipcode",
                "hseId"
            })
            public static class Street1 {

                @XmlElement(name = "house_number")
                protected int houseNumber;
                @XmlElement(required = true)
                protected Object fraction;
                @XmlElement(required = true)
                protected String direction;
                @XmlElement(name = "street_name", required = true)
                protected String streetName;
                @XmlElement(required = true)
                protected String suffix;
                @XmlElement(name = "suffix_dir", required = true)
                protected Object suffixDir;
                protected int zipcode;
                @XmlElement(name = "hse_id")
                protected int hseId;

                /**
                 * Gets the value of the houseNumber property.
                 * 
                 */
                public int getHouseNumber() {
                    return houseNumber;
                }

                /**
                 * Sets the value of the houseNumber property.
                 * 
                 */
                public void setHouseNumber(int value) {
                    this.houseNumber = value;
                }

                /**
                 * Gets the value of the fraction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getFraction() {
                    return fraction;
                }

                /**
                 * Sets the value of the fraction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setFraction(Object value) {
                    this.fraction = value;
                }

                /**
                 * Gets the value of the direction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDirection() {
                    return direction;
                }

                /**
                 * Sets the value of the direction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDirection(String value) {
                    this.direction = value;
                }

                /**
                 * Gets the value of the streetName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreetName() {
                    return streetName;
                }

                /**
                 * Sets the value of the streetName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreetName(String value) {
                    this.streetName = value;
                }

                /**
                 * Gets the value of the suffix property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSuffix() {
                    return suffix;
                }

                /**
                 * Sets the value of the suffix property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSuffix(String value) {
                    this.suffix = value;
                }

                /**
                 * Gets the value of the suffixDir property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getSuffixDir() {
                    return suffixDir;
                }

                /**
                 * Sets the value of the suffixDir property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setSuffixDir(Object value) {
                    this.suffixDir = value;
                }

                /**
                 * Gets the value of the zipcode property.
                 * 
                 */
                public int getZipcode() {
                    return zipcode;
                }

                /**
                 * Sets the value of the zipcode property.
                 * 
                 */
                public void setZipcode(int value) {
                    this.zipcode = value;
                }

                /**
                 * Gets the value of the hseId property.
                 * 
                 */
                public int getHseId() {
                    return hseId;
                }

                /**
                 * Sets the value of the hseId property.
                 * 
                 */
                public void setHseId(int value) {
                    this.hseId = value;
                }

            }

        }

    }

}
