//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:58:23 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.itafin.addressvalidation.personator;
