//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:58:23 PM PDT 
//


package com.itafin.addressvalidation.personator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Actions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Columns" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Options" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Records">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RequestRecord" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TransmissionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actions",
    "columns",
    "customerID",
    "options",
    "records",
    "transmissionReference"
})
@XmlRootElement(name = "Request", namespace = "")
public class PersonatorRequest {

    @XmlElement(name = "Actions", namespace = "", required = true)
    protected String actions;
    @XmlElement(name = "Columns", namespace = "", required = true)
    protected String columns;
    @XmlElement(name = "CustomerID", namespace = "", required = true)
    protected String customerID;
    @XmlElement(name = "Options", namespace = "", required = true)
    protected String options;
    @XmlElement(name = "Records", namespace = "", required = true)
    protected PersonatorRequest.Records records;
    @XmlElement(name = "TransmissionReference", namespace = "", required = true)
    protected String transmissionReference;

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActions(String value) {
        this.actions = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumns(String value) {
        this.columns = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptions(String value) {
        this.options = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link PersonatorRequest.Records }
     *     
     */
    public PersonatorRequest.Records getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonatorRequest.Records }
     *     
     */
    public void setRecords(PersonatorRequest.Records value) {
        this.records = value;
    }

    /**
     * Gets the value of the transmissionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionReference() {
        return transmissionReference;
    }

    /**
     * Sets the value of the transmissionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionReference(String value) {
        this.transmissionReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RequestRecord" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestRecord"
    })
    public static class Records {

        @XmlElement(name = "RequestRecord", namespace = "", required = true)
        protected List<PersonatorRequest.Records.RequestRecord> requestRecord;

        /**
         * Gets the value of the requestRecord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requestRecord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequestRecord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonatorRequest.Records.RequestRecord }
         * 
         * 
         */
        public List<PersonatorRequest.Records.RequestRecord> getRequestRecord() {
            if (requestRecord == null) {
                requestRecord = new ArrayList<PersonatorRequest.Records.RequestRecord>();
            }
            return this.requestRecord;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressLine1",
            "addressLine2",
            "freeform",
            "city",
            "postalCode",
            "state",
            "companyName"
        })
        public static class RequestRecord {

            @XmlElement(name = "AddressLine1", namespace = "", required = true)
            protected String addressLine1;
            @XmlElement(name = "AddressLine2", namespace = "", required = true)
            protected String addressLine2;
            @XmlElement(name = "Freeform", namespace = "", required = true)
            protected String freeform;
            @XmlElement(name = "City", namespace = "", required = true)
            protected String city;
            @XmlElement(name = "PostalCode", namespace = "", required = true)
            protected String postalCode;
            @XmlElement(name = "State", namespace = "", required = true)
            protected String state;
            @XmlElement(name = "CompanyName", namespace = "", required = true)
            protected String companyName;

            /**
             * Gets the value of the addressLine1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressLine1() {
                return addressLine1;
            }

            /**
             * Sets the value of the addressLine1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressLine1(String value) {
                this.addressLine1 = value;
            }
            
            /**
             * Gets the value of the addressLine2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressLine2() {
                return addressLine2;
            }

            /**
             * Sets the value of the addressLine2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressLine2(String value) {
                this.addressLine2 = value;
            }
            
            /**
             * Gets the value of the freeform property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFeeform() {
                return freeform;
            }

            /**
             * Sets the value of the freeform property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFreeform(String value) {
                this.freeform = value;
            }
            
            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the postalCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostalCode() {
                return postalCode;
            }

            /**
             * Sets the value of the postalCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostalCode(String value) {
                this.postalCode = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }
            
            /**
             * Gets the value of the companyName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompanyName() {
                return companyName;
            }

            /**
             * Sets the value of the companyName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompanyName(String value) {
                this.companyName = value;
            }

        }

    }

}
