//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:58:23 PM PDT 
//


package com.itafin.addressvalidation.personator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Records" type="{http://schemas.datacontract.org/2004/07/WcfServiceMD.mdContactVerify}ArrayOfResponseRecord" minOccurs="0"/>
 *         &lt;element name="TotalRecords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransmissionReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TransmissionResults" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "records",
    "totalRecords",
    "transmissionReference",
    "transmissionResults",
    "version"
})
public class PersonatorResponse {

    @XmlElement(name = "Records", nillable = true)
    protected ArrayOfResponseRecord records;
    @XmlElement(name = "TotalRecords", nillable = true)
    protected String totalRecords;
    @XmlElement(name = "TransmissionReference", nillable = true)
    protected String transmissionReference;
    @XmlElement(name = "TransmissionResults", nillable = true)
    protected String transmissionResults;
    @XmlElement(name = "Version", nillable = true)
    protected String version;

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfResponseRecord }
     *     
     */
    public ArrayOfResponseRecord getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfResponseRecord }
     *     
     */
    public void setRecords(ArrayOfResponseRecord value) {
        this.records = value;
    }

    /**
     * Gets the value of the totalRecords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRecords() {
        return totalRecords;
    }

    /**
     * Sets the value of the totalRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRecords(String value) {
        this.totalRecords = value;
    }

    /**
     * Gets the value of the transmissionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionReference() {
        return transmissionReference;
    }

    /**
     * Sets the value of the transmissionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionReference(String value) {
        this.transmissionReference = value;
    }

    /**
     * Gets the value of the transmissionResults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmissionResults() {
        return transmissionResults;
    }

    /**
     * Sets the value of the transmissionResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmissionResults(String value) {
        this.transmissionResults = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
