//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:58:23 PM PDT 
//


package com.itafin.addressvalidation.personator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.itafin.addressvalidation.util.MDStatus;


/**
 * <p>Java class for ResponseRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AddressDeliveryInstallation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressExtras" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressHouseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLockBox" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressPostDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressPreDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressPrivateMailboxName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressPrivateMailboxRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressRouteService" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressStreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressStreetSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressSuiteName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressSuiteNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSACode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSADivisionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSADivisionLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSADivisionTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSALevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CBSATitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CarrierRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CensusBlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CensusKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CensusTract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChildrenAgeRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CityAbbreviation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CongressionalDistrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountyFIPS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountySubdivisionName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CreditCardUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateOfDeath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryPointCheckDigit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryPointCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DemographicsGender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DemographicsResults" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DomainName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Education" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ElementarySchoolDistrictCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ElementarySchoolDistrictName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EthnicCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EthnicGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Gender2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseholdIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseholdSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LengthOfResidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MailboxName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MelissaAddressKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MelissaAddressKeyBase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MoveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameFirst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameFirst2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameFull" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLast" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameLast2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameMiddle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameMiddle2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NamePrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NamePrefix2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameSuffix2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewAreaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OwnRent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneCountryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneExtension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhonePrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlaceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlaceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Plus4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PoliticalParty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PresenceOfChildren" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PresenceOfSenior" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrivateMailBox" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordExtras" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RecordID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reserved" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Results" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Salutation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondarySchoolDistrictCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondarySchoolDistrictName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateDistrictLower" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateDistrictUpper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Suite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TopLevelDomain" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TypesOfVehicles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UTC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnifiedSchoolDistrictCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnifiedSchoolDistrictName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UrbanizationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseRecord", propOrder = {
    "addressDeliveryInstallation",
    "addressExtras",
    "addressHouseNumber",
    "addressKey",
    "addressLine1",
    "addressLine2",
    "addressLockBox",
    "addressPostDirection",
    "addressPreDirection",
    "addressPrivateMailboxName",
    "addressPrivateMailboxRange",
    "addressRouteService",
    "addressStreetName",
    "addressStreetSuffix",
    "addressSuiteName",
    "addressSuiteNumber",
    "addressTypeCode",
    "areaCode",
    "cbsaCode",
    "cbsaDivisionCode",
    "cbsaDivisionLevel",
    "cbsaDivisionTitle",
    "cbsaLevel",
    "cbsaTitle",
    "carrierRoute",
    "censusBlock",
    "censusKey",
    "censusTract",
    "childrenAgeRange",
    "city",
    "cityAbbreviation",
    "companyName",
    "congressionalDistrict",
    "countryCode",
    "countryName",
    "countyFIPS",
    "countyName",
    "countySubdivisionCode",
    "countySubdivisionName",
    "creditCardUser",
    "dateOfBirth",
    "dateOfDeath",
    "deliveryIndicator",
    "deliveryPointCheckDigit",
    "deliveryPointCode",
    "demographicsGender",
    "demographicsResults",
    "domainName",
    "education",
    "elementarySchoolDistrictCode",
    "elementarySchoolDistrictName",
    "emailAddress",
    "ethnicCode",
    "ethnicGroup",
    "gender",
    "gender2",
    "householdIncome",
    "householdSize",
    "latitude",
    "lengthOfResidence",
    "longitude",
    "mailboxName",
    "maritalStatus",
    "melissaAddressKey",
    "melissaAddressKeyBase",
    "moveDate",
    "nameFirst",
    "nameFirst2",
    "nameFull",
    "nameLast",
    "nameLast2",
    "nameMiddle",
    "nameMiddle2",
    "namePrefix",
    "namePrefix2",
    "nameSuffix",
    "nameSuffix2",
    "newAreaCode",
    "occupation",
    "ownRent",
    "phoneCountryCode",
    "phoneCountryName",
    "phoneExtension",
    "phoneNumber",
    "phonePrefix",
    "phoneSuffix",
    "placeCode",
    "placeName",
    "plus4",
    "politicalParty",
    "postalCode",
    "presenceOfChildren",
    "presenceOfSenior",
    "privateMailBox",
    "recordExtras",
    "recordID",
    "reserved",
    "results",
    "salutation",
    "secondarySchoolDistrictCode",
    "secondarySchoolDistrictName",
    "state",
    "stateDistrictLower",
    "stateDistrictUpper",
    "stateName",
    "suite",
    "topLevelDomain",
    "typesOfVehicles",
    "utc",
    "unifiedSchoolDistrictCode",
    "unifiedSchoolDistrictName",
    "urbanizationName"
})
public class ResponseRecord {

    @XmlElement(name = "AddressDeliveryInstallation", nillable = true)
    protected String addressDeliveryInstallation;
    @XmlElement(name = "AddressExtras", nillable = true)
    protected String addressExtras;
    @XmlElement(name = "AddressHouseNumber", nillable = true)
    protected String addressHouseNumber;
    @XmlElement(name = "AddressKey", nillable = true)
    protected String addressKey;
    @XmlElement(name = "AddressLine1", nillable = true)
    protected String addressLine1;
    @XmlElement(name = "AddressLine2", nillable = true)
    protected String addressLine2;
    @XmlElement(name = "AddressLockBox", nillable = true)
    protected String addressLockBox;
    @XmlElement(name = "AddressPostDirection", nillable = true)
    protected String addressPostDirection;
    @XmlElement(name = "AddressPreDirection", nillable = true)
    protected String addressPreDirection;
    @XmlElement(name = "AddressPrivateMailboxName", nillable = true)
    protected String addressPrivateMailboxName;
    @XmlElement(name = "AddressPrivateMailboxRange", nillable = true)
    protected String addressPrivateMailboxRange;
    @XmlElement(name = "AddressRouteService", nillable = true)
    protected String addressRouteService;
    @XmlElement(name = "AddressStreetName", nillable = true)
    protected String addressStreetName;
    @XmlElement(name = "AddressStreetSuffix", nillable = true)
    protected String addressStreetSuffix;
    @XmlElement(name = "AddressSuiteName", nillable = true)
    protected String addressSuiteName;
    @XmlElement(name = "AddressSuiteNumber", nillable = true)
    protected String addressSuiteNumber;
    @XmlElement(name = "AddressTypeCode", nillable = true)
    protected String addressTypeCode;
    @XmlElement(name = "AreaCode", nillable = true)
    protected String areaCode;
    @XmlElement(name = "CBSACode", nillable = true)
    protected String cbsaCode;
    @XmlElement(name = "CBSADivisionCode", nillable = true)
    protected String cbsaDivisionCode;
    @XmlElement(name = "CBSADivisionLevel", nillable = true)
    protected String cbsaDivisionLevel;
    @XmlElement(name = "CBSADivisionTitle", nillable = true)
    protected String cbsaDivisionTitle;
    @XmlElement(name = "CBSALevel", nillable = true)
    protected String cbsaLevel;
    @XmlElement(name = "CBSATitle", nillable = true)
    protected String cbsaTitle;
    @XmlElement(name = "CarrierRoute", nillable = true)
    protected String carrierRoute;
    @XmlElement(name = "CensusBlock", nillable = true)
    protected String censusBlock;
    @XmlElement(name = "CensusKey", nillable = true)
    protected String censusKey;
    @XmlElement(name = "CensusTract", nillable = true)
    protected String censusTract;
    @XmlElement(name = "ChildrenAgeRange", nillable = true)
    protected String childrenAgeRange;
    @XmlElement(name = "City", nillable = true)
    protected String city;
    @XmlElement(name = "CityAbbreviation", nillable = true)
    protected String cityAbbreviation;
    @XmlElement(name = "CompanyName", nillable = true)
    protected String companyName;
    @XmlElement(name = "CongressionalDistrict", nillable = true)
    protected String congressionalDistrict;
    @XmlElement(name = "CountryCode", nillable = true)
    protected String countryCode;
    @XmlElement(name = "CountryName", nillable = true)
    protected String countryName;
    @XmlElement(name = "CountyFIPS", nillable = true)
    protected String countyFIPS;
    @XmlElement(name = "CountyName", nillable = true)
    protected String countyName;
    @XmlElement(name = "CountySubdivisionCode", nillable = true)
    protected String countySubdivisionCode;
    @XmlElement(name = "CountySubdivisionName", nillable = true)
    protected String countySubdivisionName;
    @XmlElement(name = "CreditCardUser", nillable = true)
    protected String creditCardUser;
    @XmlElement(name = "DateOfBirth", nillable = true)
    protected String dateOfBirth;
    @XmlElement(name = "DateOfDeath", nillable = true)
    protected String dateOfDeath;
    @XmlElement(name = "DeliveryIndicator", nillable = true)
    protected String deliveryIndicator;
    @XmlElement(name = "DeliveryPointCheckDigit", nillable = true)
    protected String deliveryPointCheckDigit;
    @XmlElement(name = "DeliveryPointCode", nillable = true)
    protected String deliveryPointCode;
    @XmlElement(name = "DemographicsGender", nillable = true)
    protected String demographicsGender;
    @XmlElement(name = "DemographicsResults", nillable = true)
    protected String demographicsResults;
    @XmlElement(name = "DomainName", nillable = true)
    protected String domainName;
    @XmlElement(name = "Education", nillable = true)
    protected String education;
    @XmlElement(name = "ElementarySchoolDistrictCode", nillable = true)
    protected String elementarySchoolDistrictCode;
    @XmlElement(name = "ElementarySchoolDistrictName", nillable = true)
    protected String elementarySchoolDistrictName;
    @XmlElement(name = "EmailAddress", nillable = true)
    protected String emailAddress;
    @XmlElement(name = "EthnicCode", nillable = true)
    protected String ethnicCode;
    @XmlElement(name = "EthnicGroup", nillable = true)
    protected String ethnicGroup;
    @XmlElement(name = "Gender", nillable = true)
    protected String gender;
    @XmlElement(name = "Gender2", nillable = true)
    protected String gender2;
    @XmlElement(name = "HouseholdIncome", nillable = true)
    protected String householdIncome;
    @XmlElement(name = "HouseholdSize", nillable = true)
    protected String householdSize;
    @XmlElement(name = "Latitude", nillable = true)
    protected String latitude;
    @XmlElement(name = "LengthOfResidence", nillable = true)
    protected String lengthOfResidence;
    @XmlElement(name = "Longitude", nillable = true)
    protected String longitude;
    @XmlElement(name = "MailboxName", nillable = true)
    protected String mailboxName;
    @XmlElement(name = "MaritalStatus", nillable = true)
    protected String maritalStatus;
    @XmlElement(name = "MelissaAddressKey", nillable = true)
    protected String melissaAddressKey;
    @XmlElement(name = "MelissaAddressKeyBase", nillable = true)
    protected String melissaAddressKeyBase;
    @XmlElement(name = "MoveDate", nillable = true)
    protected String moveDate;
    @XmlElement(name = "NameFirst", nillable = true)
    protected String nameFirst;
    @XmlElement(name = "NameFirst2", nillable = true)
    protected String nameFirst2;
    @XmlElement(name = "NameFull", nillable = true)
    protected String nameFull;
    @XmlElement(name = "NameLast", nillable = true)
    protected String nameLast;
    @XmlElement(name = "NameLast2", nillable = true)
    protected String nameLast2;
    @XmlElement(name = "NameMiddle", nillable = true)
    protected String nameMiddle;
    @XmlElement(name = "NameMiddle2", nillable = true)
    protected String nameMiddle2;
    @XmlElement(name = "NamePrefix", nillable = true)
    protected String namePrefix;
    @XmlElement(name = "NamePrefix2", nillable = true)
    protected String namePrefix2;
    @XmlElement(name = "NameSuffix", nillable = true)
    protected String nameSuffix;
    @XmlElement(name = "NameSuffix2", nillable = true)
    protected String nameSuffix2;
    @XmlElement(name = "NewAreaCode", nillable = true)
    protected String newAreaCode;
    @XmlElement(name = "Occupation", nillable = true)
    protected String occupation;
    @XmlElement(name = "OwnRent", nillable = true)
    protected String ownRent;
    @XmlElement(name = "PhoneCountryCode", nillable = true)
    protected String phoneCountryCode;
    @XmlElement(name = "PhoneCountryName", nillable = true)
    protected String phoneCountryName;
    @XmlElement(name = "PhoneExtension", nillable = true)
    protected String phoneExtension;
    @XmlElement(name = "PhoneNumber", nillable = true)
    protected String phoneNumber;
    @XmlElement(name = "PhonePrefix", nillable = true)
    protected String phonePrefix;
    @XmlElement(name = "PhoneSuffix", nillable = true)
    protected String phoneSuffix;
    @XmlElement(name = "PlaceCode", nillable = true)
    protected String placeCode;
    @XmlElement(name = "PlaceName", nillable = true)
    protected String placeName;
    @XmlElement(name = "Plus4", nillable = true)
    protected String plus4;
    @XmlElement(name = "PoliticalParty", nillable = true)
    protected String politicalParty;
    @XmlElement(name = "PostalCode", nillable = true)
    protected String postalCode;
    @XmlElement(name = "PresenceOfChildren", nillable = true)
    protected String presenceOfChildren;
    @XmlElement(name = "PresenceOfSenior", nillable = true)
    protected String presenceOfSenior;
    @XmlElement(name = "PrivateMailBox", nillable = true)
    protected String privateMailBox;
    @XmlElement(name = "RecordExtras", nillable = true)
    protected String recordExtras;
    @XmlElement(name = "RecordID", nillable = true)
    protected String recordID;
    @XmlElement(name = "Reserved", nillable = true)
    protected String reserved;
    @XmlElement(name = "Results", nillable = true)
    protected String results;
    @XmlElement(name = "Salutation", nillable = true)
    protected String salutation;
    @XmlElement(name = "SecondarySchoolDistrictCode", nillable = true)
    protected String secondarySchoolDistrictCode;
    @XmlElement(name = "SecondarySchoolDistrictName", nillable = true)
    protected String secondarySchoolDistrictName;
    @XmlElement(name = "State", nillable = true)
    protected String state;
    @XmlElement(name = "StateDistrictLower", nillable = true)
    protected String stateDistrictLower;
    @XmlElement(name = "StateDistrictUpper", nillable = true)
    protected String stateDistrictUpper;
    @XmlElement(name = "StateName", nillable = true)
    protected String stateName;
    @XmlElement(name = "Suite", nillable = true)
    protected String suite;
    @XmlElement(name = "TopLevelDomain", nillable = true)
    protected String topLevelDomain;
    @XmlElement(name = "TypesOfVehicles", nillable = true)
    protected String typesOfVehicles;
    @XmlElement(name = "UTC", nillable = true)
    protected String utc;
    @XmlElement(name = "UnifiedSchoolDistrictCode", nillable = true)
    protected String unifiedSchoolDistrictCode;
    @XmlElement(name = "UnifiedSchoolDistrictName", nillable = true)
    protected String unifiedSchoolDistrictName;
    @XmlElement(name = "UrbanizationName", nillable = true)
    protected String urbanizationName;
    
    @XmlTransient
    private MDStatus status = new MDStatus();
    
	public boolean isSuccess() {
		return status.isAddressSuccess();
	}

	public boolean isError() {
		return status.isAddressError();
	}

	public boolean isMultiMatch() {
		return status.isMultiMatch();
	}

	public void setResultCode(String resultCode) {
		status.setResultCode(resultCode);
	}

    /**
     * Gets the value of the addressDeliveryInstallation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressDeliveryInstallation() {
        return addressDeliveryInstallation;
    }

    /**
     * Sets the value of the addressDeliveryInstallation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressDeliveryInstallation(String value) {
        this.addressDeliveryInstallation = value;
    }

    /**
     * Gets the value of the addressExtras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressExtras() {
        return addressExtras;
    }

    /**
     * Sets the value of the addressExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressExtras(String value) {
        this.addressExtras = value;
    }

    /**
     * Gets the value of the addressHouseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressHouseNumber() {
        return addressHouseNumber;
    }

    /**
     * Sets the value of the addressHouseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressHouseNumber(String value) {
        this.addressHouseNumber = value;
    }

    /**
     * Gets the value of the addressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressKey() {
        return addressKey;
    }

    /**
     * Sets the value of the addressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressKey(String value) {
        this.addressKey = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLockBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLockBox() {
        return addressLockBox;
    }

    /**
     * Sets the value of the addressLockBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLockBox(String value) {
        this.addressLockBox = value;
    }

    /**
     * Gets the value of the addressPostDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPostDirection() {
        return addressPostDirection;
    }

    /**
     * Sets the value of the addressPostDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPostDirection(String value) {
        this.addressPostDirection = value;
    }

    /**
     * Gets the value of the addressPreDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPreDirection() {
        return addressPreDirection;
    }

    /**
     * Sets the value of the addressPreDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPreDirection(String value) {
        this.addressPreDirection = value;
    }

    /**
     * Gets the value of the addressPrivateMailboxName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPrivateMailboxName() {
        return addressPrivateMailboxName;
    }

    /**
     * Sets the value of the addressPrivateMailboxName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPrivateMailboxName(String value) {
        this.addressPrivateMailboxName = value;
    }

    /**
     * Gets the value of the addressPrivateMailboxRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressPrivateMailboxRange() {
        return addressPrivateMailboxRange;
    }

    /**
     * Sets the value of the addressPrivateMailboxRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressPrivateMailboxRange(String value) {
        this.addressPrivateMailboxRange = value;
    }

    /**
     * Gets the value of the addressRouteService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressRouteService() {
        return addressRouteService;
    }

    /**
     * Sets the value of the addressRouteService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressRouteService(String value) {
        this.addressRouteService = value;
    }

    /**
     * Gets the value of the addressStreetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreetName() {
        return addressStreetName;
    }

    /**
     * Sets the value of the addressStreetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreetName(String value) {
        this.addressStreetName = value;
    }

    /**
     * Gets the value of the addressStreetSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStreetSuffix() {
        return addressStreetSuffix;
    }

    /**
     * Sets the value of the addressStreetSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStreetSuffix(String value) {
        this.addressStreetSuffix = value;
    }

    /**
     * Gets the value of the addressSuiteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressSuiteName() {
        return addressSuiteName;
    }

    /**
     * Sets the value of the addressSuiteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressSuiteName(String value) {
        this.addressSuiteName = value;
    }

    /**
     * Gets the value of the addressSuiteNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressSuiteNumber() {
        return addressSuiteNumber;
    }

    /**
     * Sets the value of the addressSuiteNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressSuiteNumber(String value) {
        this.addressSuiteNumber = value;
    }

    /**
     * Gets the value of the addressTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressTypeCode() {
        return addressTypeCode;
    }

    /**
     * Sets the value of the addressTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressTypeCode(String value) {
        this.addressTypeCode = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the cbsaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSACode() {
        return cbsaCode;
    }

    /**
     * Sets the value of the cbsaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSACode(String value) {
        this.cbsaCode = value;
    }

    /**
     * Gets the value of the cbsaDivisionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSADivisionCode() {
        return cbsaDivisionCode;
    }

    /**
     * Sets the value of the cbsaDivisionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSADivisionCode(String value) {
        this.cbsaDivisionCode = value;
    }

    /**
     * Gets the value of the cbsaDivisionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSADivisionLevel() {
        return cbsaDivisionLevel;
    }

    /**
     * Sets the value of the cbsaDivisionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSADivisionLevel(String value) {
        this.cbsaDivisionLevel = value;
    }

    /**
     * Gets the value of the cbsaDivisionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSADivisionTitle() {
        return cbsaDivisionTitle;
    }

    /**
     * Sets the value of the cbsaDivisionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSADivisionTitle(String value) {
        this.cbsaDivisionTitle = value;
    }

    /**
     * Gets the value of the cbsaLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSALevel() {
        return cbsaLevel;
    }

    /**
     * Sets the value of the cbsaLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSALevel(String value) {
        this.cbsaLevel = value;
    }

    /**
     * Gets the value of the cbsaTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBSATitle() {
        return cbsaTitle;
    }

    /**
     * Sets the value of the cbsaTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBSATitle(String value) {
        this.cbsaTitle = value;
    }

    /**
     * Gets the value of the carrierRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierRoute() {
        return carrierRoute;
    }

    /**
     * Sets the value of the carrierRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierRoute(String value) {
        this.carrierRoute = value;
    }

    /**
     * Gets the value of the censusBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensusBlock() {
        return censusBlock;
    }

    /**
     * Sets the value of the censusBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensusBlock(String value) {
        this.censusBlock = value;
    }

    /**
     * Gets the value of the censusKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensusKey() {
        return censusKey;
    }

    /**
     * Sets the value of the censusKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensusKey(String value) {
        this.censusKey = value;
    }

    /**
     * Gets the value of the censusTract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensusTract() {
        return censusTract;
    }

    /**
     * Sets the value of the censusTract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensusTract(String value) {
        this.censusTract = value;
    }

    /**
     * Gets the value of the childrenAgeRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildrenAgeRange() {
        return childrenAgeRange;
    }

    /**
     * Sets the value of the childrenAgeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildrenAgeRange(String value) {
        this.childrenAgeRange = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the cityAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityAbbreviation() {
        return cityAbbreviation;
    }

    /**
     * Sets the value of the cityAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityAbbreviation(String value) {
        this.cityAbbreviation = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the congressionalDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCongressionalDistrict() {
        return congressionalDistrict;
    }

    /**
     * Sets the value of the congressionalDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCongressionalDistrict(String value) {
        this.congressionalDistrict = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the countyFIPS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountyFIPS() {
        return countyFIPS;
    }

    /**
     * Sets the value of the countyFIPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountyFIPS(String value) {
        this.countyFIPS = value;
    }

    /**
     * Gets the value of the countyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * Sets the value of the countyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountyName(String value) {
        this.countyName = value;
    }

    /**
     * Gets the value of the countySubdivisionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountySubdivisionCode() {
        return countySubdivisionCode;
    }

    /**
     * Sets the value of the countySubdivisionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountySubdivisionCode(String value) {
        this.countySubdivisionCode = value;
    }

    /**
     * Gets the value of the countySubdivisionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountySubdivisionName() {
        return countySubdivisionName;
    }

    /**
     * Sets the value of the countySubdivisionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountySubdivisionName(String value) {
        this.countySubdivisionName = value;
    }

    /**
     * Gets the value of the creditCardUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCardUser() {
        return creditCardUser;
    }

    /**
     * Sets the value of the creditCardUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCardUser(String value) {
        this.creditCardUser = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the dateOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfDeath() {
        return dateOfDeath;
    }

    /**
     * Sets the value of the dateOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfDeath(String value) {
        this.dateOfDeath = value;
    }

    /**
     * Gets the value of the deliveryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryIndicator() {
        return deliveryIndicator;
    }

    /**
     * Sets the value of the deliveryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryIndicator(String value) {
        this.deliveryIndicator = value;
    }

    /**
     * Gets the value of the deliveryPointCheckDigit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPointCheckDigit() {
        return deliveryPointCheckDigit;
    }

    /**
     * Sets the value of the deliveryPointCheckDigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPointCheckDigit(String value) {
        this.deliveryPointCheckDigit = value;
    }

    /**
     * Gets the value of the deliveryPointCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPointCode() {
        return deliveryPointCode;
    }

    /**
     * Sets the value of the deliveryPointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPointCode(String value) {
        this.deliveryPointCode = value;
    }

    /**
     * Gets the value of the demographicsGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemographicsGender() {
        return demographicsGender;
    }

    /**
     * Sets the value of the demographicsGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemographicsGender(String value) {
        this.demographicsGender = value;
    }

    /**
     * Gets the value of the demographicsResults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemographicsResults() {
        return demographicsResults;
    }

    /**
     * Sets the value of the demographicsResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemographicsResults(String value) {
        this.demographicsResults = value;
    }

    /**
     * Gets the value of the domainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * Sets the value of the domainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainName(String value) {
        this.domainName = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the elementarySchoolDistrictCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementarySchoolDistrictCode() {
        return elementarySchoolDistrictCode;
    }

    /**
     * Sets the value of the elementarySchoolDistrictCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementarySchoolDistrictCode(String value) {
        this.elementarySchoolDistrictCode = value;
    }

    /**
     * Gets the value of the elementarySchoolDistrictName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementarySchoolDistrictName() {
        return elementarySchoolDistrictName;
    }

    /**
     * Sets the value of the elementarySchoolDistrictName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementarySchoolDistrictName(String value) {
        this.elementarySchoolDistrictName = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the ethnicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicCode() {
        return ethnicCode;
    }

    /**
     * Sets the value of the ethnicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicCode(String value) {
        this.ethnicCode = value;
    }

    /**
     * Gets the value of the ethnicGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * Sets the value of the ethnicGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicGroup(String value) {
        this.ethnicGroup = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the gender2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender2() {
        return gender2;
    }

    /**
     * Sets the value of the gender2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender2(String value) {
        this.gender2 = value;
    }

    /**
     * Gets the value of the householdIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseholdIncome() {
        return householdIncome;
    }

    /**
     * Sets the value of the householdIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseholdIncome(String value) {
        this.householdIncome = value;
    }

    /**
     * Gets the value of the householdSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseholdSize() {
        return householdSize;
    }

    /**
     * Sets the value of the householdSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseholdSize(String value) {
        this.householdSize = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the lengthOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthOfResidence() {
        return lengthOfResidence;
    }

    /**
     * Sets the value of the lengthOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthOfResidence(String value) {
        this.lengthOfResidence = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the mailboxName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailboxName() {
        return mailboxName;
    }

    /**
     * Sets the value of the mailboxName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailboxName(String value) {
        this.mailboxName = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the melissaAddressKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMelissaAddressKey() {
        return melissaAddressKey;
    }

    /**
     * Sets the value of the melissaAddressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMelissaAddressKey(String value) {
        this.melissaAddressKey = value;
    }

    /**
     * Gets the value of the melissaAddressKeyBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMelissaAddressKeyBase() {
        return melissaAddressKeyBase;
    }

    /**
     * Sets the value of the melissaAddressKeyBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMelissaAddressKeyBase(String value) {
        this.melissaAddressKeyBase = value;
    }

    /**
     * Gets the value of the moveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveDate() {
        return moveDate;
    }

    /**
     * Sets the value of the moveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveDate(String value) {
        this.moveDate = value;
    }

    /**
     * Gets the value of the nameFirst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFirst() {
        return nameFirst;
    }

    /**
     * Sets the value of the nameFirst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFirst(String value) {
        this.nameFirst = value;
    }

    /**
     * Gets the value of the nameFirst2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFirst2() {
        return nameFirst2;
    }

    /**
     * Sets the value of the nameFirst2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFirst2(String value) {
        this.nameFirst2 = value;
    }

    /**
     * Gets the value of the nameFull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFull() {
        return nameFull;
    }

    /**
     * Sets the value of the nameFull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFull(String value) {
        this.nameFull = value;
    }

    /**
     * Gets the value of the nameLast property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLast() {
        return nameLast;
    }

    /**
     * Sets the value of the nameLast property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLast(String value) {
        this.nameLast = value;
    }

    /**
     * Gets the value of the nameLast2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLast2() {
        return nameLast2;
    }

    /**
     * Sets the value of the nameLast2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLast2(String value) {
        this.nameLast2 = value;
    }

    /**
     * Gets the value of the nameMiddle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameMiddle() {
        return nameMiddle;
    }

    /**
     * Sets the value of the nameMiddle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameMiddle(String value) {
        this.nameMiddle = value;
    }

    /**
     * Gets the value of the nameMiddle2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameMiddle2() {
        return nameMiddle2;
    }

    /**
     * Sets the value of the nameMiddle2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameMiddle2(String value) {
        this.nameMiddle2 = value;
    }

    /**
     * Gets the value of the namePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePrefix() {
        return namePrefix;
    }

    /**
     * Sets the value of the namePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePrefix(String value) {
        this.namePrefix = value;
    }

    /**
     * Gets the value of the namePrefix2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePrefix2() {
        return namePrefix2;
    }

    /**
     * Sets the value of the namePrefix2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePrefix2(String value) {
        this.namePrefix2 = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the nameSuffix2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix2() {
        return nameSuffix2;
    }

    /**
     * Sets the value of the nameSuffix2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix2(String value) {
        this.nameSuffix2 = value;
    }

    /**
     * Gets the value of the newAreaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewAreaCode() {
        return newAreaCode;
    }

    /**
     * Sets the value of the newAreaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewAreaCode(String value) {
        this.newAreaCode = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the ownRent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnRent() {
        return ownRent;
    }

    /**
     * Sets the value of the ownRent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnRent(String value) {
        this.ownRent = value;
    }

    /**
     * Gets the value of the phoneCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneCountryCode() {
        return phoneCountryCode;
    }

    /**
     * Sets the value of the phoneCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneCountryCode(String value) {
        this.phoneCountryCode = value;
    }

    /**
     * Gets the value of the phoneCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneCountryName() {
        return phoneCountryName;
    }

    /**
     * Sets the value of the phoneCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneCountryName(String value) {
        this.phoneCountryName = value;
    }

    /**
     * Gets the value of the phoneExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneExtension() {
        return phoneExtension;
    }

    /**
     * Sets the value of the phoneExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneExtension(String value) {
        this.phoneExtension = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the phonePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhonePrefix() {
        return phonePrefix;
    }

    /**
     * Sets the value of the phonePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhonePrefix(String value) {
        this.phonePrefix = value;
    }

    /**
     * Gets the value of the phoneSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneSuffix() {
        return phoneSuffix;
    }

    /**
     * Sets the value of the phoneSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneSuffix(String value) {
        this.phoneSuffix = value;
    }

    /**
     * Gets the value of the placeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceCode() {
        return placeCode;
    }

    /**
     * Sets the value of the placeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceCode(String value) {
        this.placeCode = value;
    }

    /**
     * Gets the value of the placeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceName() {
        return placeName;
    }

    /**
     * Sets the value of the placeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceName(String value) {
        this.placeName = value;
    }

    /**
     * Gets the value of the plus4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlus4() {
        return plus4;
    }

    /**
     * Sets the value of the plus4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlus4(String value) {
        this.plus4 = value;
    }

    /**
     * Gets the value of the politicalParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoliticalParty() {
        return politicalParty;
    }

    /**
     * Sets the value of the politicalParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoliticalParty(String value) {
        this.politicalParty = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the presenceOfChildren property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresenceOfChildren() {
        return presenceOfChildren;
    }

    /**
     * Sets the value of the presenceOfChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresenceOfChildren(String value) {
        this.presenceOfChildren = value;
    }

    /**
     * Gets the value of the presenceOfSenior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresenceOfSenior() {
        return presenceOfSenior;
    }

    /**
     * Sets the value of the presenceOfSenior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresenceOfSenior(String value) {
        this.presenceOfSenior = value;
    }

    /**
     * Gets the value of the privateMailBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateMailBox() {
        return privateMailBox;
    }

    /**
     * Sets the value of the privateMailBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateMailBox(String value) {
        this.privateMailBox = value;
    }

    /**
     * Gets the value of the recordExtras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordExtras() {
        return recordExtras;
    }

    /**
     * Sets the value of the recordExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordExtras(String value) {
        this.recordExtras = value;
    }

    /**
     * Gets the value of the recordID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordID() {
        return recordID;
    }

    /**
     * Sets the value of the recordID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordID(String value) {
        this.recordID = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReserved(String value) {
        this.reserved = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResults(String value) {
        this.results = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutation(String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the secondarySchoolDistrictCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondarySchoolDistrictCode() {
        return secondarySchoolDistrictCode;
    }

    /**
     * Sets the value of the secondarySchoolDistrictCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondarySchoolDistrictCode(String value) {
        this.secondarySchoolDistrictCode = value;
    }

    /**
     * Gets the value of the secondarySchoolDistrictName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondarySchoolDistrictName() {
        return secondarySchoolDistrictName;
    }

    /**
     * Sets the value of the secondarySchoolDistrictName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondarySchoolDistrictName(String value) {
        this.secondarySchoolDistrictName = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the stateDistrictLower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDistrictLower() {
        return stateDistrictLower;
    }

    /**
     * Sets the value of the stateDistrictLower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDistrictLower(String value) {
        this.stateDistrictLower = value;
    }

    /**
     * Gets the value of the stateDistrictUpper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDistrictUpper() {
        return stateDistrictUpper;
    }

    /**
     * Sets the value of the stateDistrictUpper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDistrictUpper(String value) {
        this.stateDistrictUpper = value;
    }

    /**
     * Gets the value of the stateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * Sets the value of the stateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateName(String value) {
        this.stateName = value;
    }

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuite(String value) {
        this.suite = value;
    }

    /**
     * Gets the value of the topLevelDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopLevelDomain() {
        return topLevelDomain;
    }

    /**
     * Sets the value of the topLevelDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopLevelDomain(String value) {
        this.topLevelDomain = value;
    }

    /**
     * Gets the value of the typesOfVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypesOfVehicles() {
        return typesOfVehicles;
    }

    /**
     * Sets the value of the typesOfVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypesOfVehicles(String value) {
        this.typesOfVehicles = value;
    }

    /**
     * Gets the value of the utc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUTC() {
        return utc;
    }

    /**
     * Sets the value of the utc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUTC(String value) {
        this.utc = value;
    }

    /**
     * Gets the value of the unifiedSchoolDistrictCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnifiedSchoolDistrictCode() {
        return unifiedSchoolDistrictCode;
    }

    /**
     * Sets the value of the unifiedSchoolDistrictCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnifiedSchoolDistrictCode(String value) {
        this.unifiedSchoolDistrictCode = value;
    }

    /**
     * Gets the value of the unifiedSchoolDistrictName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnifiedSchoolDistrictName() {
        return unifiedSchoolDistrictName;
    }

    /**
     * Sets the value of the unifiedSchoolDistrictName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnifiedSchoolDistrictName(String value) {
        this.unifiedSchoolDistrictName = value;
    }

    /**
     * Gets the value of the urbanizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrbanizationName() {
        return urbanizationName;
    }

    /**
     * Sets the value of the urbanizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrbanizationName(String value) {
        this.urbanizationName = value;
    }

	public MDStatus getStatus() {
		return status;
	}

	public void setStatus(MDStatus status) {
		this.status = status;
	}

}
