//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 02:47:07 PM PST 
//


package com.itafin.boe.geo.response.exactmatch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="coords">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="layers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="layer" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fields">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="field" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "location",
    "coords",
    "layers"
})
@XmlRootElement(name = "Address-Response")
public class AddressResponse {

    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected AddressResponse.Location location;
    @XmlElement(required = true)
    protected AddressResponse.Coords coords;
    @XmlElement(required = true)
    protected AddressResponse.Layers layers;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link AddressResponse.Location }
     *     
     */
    public AddressResponse.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressResponse.Location }
     *     
     */
    public void setLocation(AddressResponse.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the coords property.
     * 
     * @return
     *     possible object is
     *     {@link AddressResponse.Coords }
     *     
     */
    public AddressResponse.Coords getCoords() {
        return coords;
    }

    /**
     * Sets the value of the coords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressResponse.Coords }
     *     
     */
    public void setCoords(AddressResponse.Coords value) {
        this.coords = value;
    }

    /**
     * Gets the value of the layers property.
     * 
     * @return
     *     possible object is
     *     {@link AddressResponse.Layers }
     *     
     */
    public AddressResponse.Layers getLayers() {
        return layers;
    }

    /**
     * Sets the value of the layers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressResponse.Layers }
     *     
     */
    public void setLayers(AddressResponse.Layers value) {
        this.layers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "x",
        "y",
        "longitude",
        "latitude"
    })
    public static class Coords {

        protected double x;
        protected double y;
        protected double longitude;
        protected double latitude;

        /**
         * Gets the value of the x property.
         * 
         */
        public double getX() {
            return x;
        }

        /**
         * Sets the value of the x property.
         * 
         */
        public void setX(double value) {
            this.x = value;
        }

        /**
         * Gets the value of the y property.
         * 
         */
        public double getY() {
            return y;
        }

        /**
         * Sets the value of the y property.
         * 
         */
        public void setY(double value) {
            this.y = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         */
        public double getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         */
        public void setLongitude(double value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         */
        public double getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         */
        public void setLatitude(double value) {
            this.latitude = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="layer" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fields">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="field" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "layer"
    })
    public static class Layers {

        @XmlElement(required = true)
        protected List<AddressResponse.Layers.Layer> layer;

        /**
         * Gets the value of the layer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the layer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLayer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AddressResponse.Layers.Layer }
         * 
         * 
         */
        public List<AddressResponse.Layers.Layer> getLayer() {
            if (layer == null) {
                layer = new ArrayList<AddressResponse.Layers.Layer>();
            }
            return this.layer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fields">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="field" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fields"
        })
        public static class Layer {

            @XmlElement(required = true)
            protected AddressResponse.Layers.Layer.Fields fields;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the fields property.
             * 
             * @return
             *     possible object is
             *     {@link AddressResponse.Layers.Layer.Fields }
             *     
             */
            public AddressResponse.Layers.Layer.Fields getFields() {
                return fields;
            }

            /**
             * Sets the value of the fields property.
             * 
             * @param value
             *     allowed object is
             *     {@link AddressResponse.Layers.Layer.Fields }
             *     
             */
            public void setFields(AddressResponse.Layers.Layer.Fields value) {
                this.fields = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="field" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "field"
            })
            public static class Fields {

                @XmlElement(required = true)
                protected List<AddressResponse.Layers.Layer.Fields.Field> field;

                /**
                 * Gets the value of the field property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the field property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getField().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link AddressResponse.Layers.Layer.Fields.Field }
                 * 
                 * 
                 */
                public List<AddressResponse.Layers.Layer.Fields.Field> getField() {
                    if (field == null) {
                        field = new ArrayList<AddressResponse.Layers.Layer.Fields.Field>();
                    }
                    return this.field;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "fieldName",
                    "value"
                })
                public static class Field {

                    @XmlElement(required = true)
                    protected String fieldName;
                    protected String value;

                    /**
                     * Gets the value of the fieldName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFieldName() {
                        return fieldName;
                    }

                    /**
                     * Sets the value of the fieldName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFieldName(String value) {
                        this.fieldName = value;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="house_number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="fraction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="direction" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="street_name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="suffix_dir" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="zipcode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="hse_id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address",
        "houseNumber",
        "fraction",
        "direction",
        "streetName",
        "suffix",
        "suffixDir",
        "zipcode",
        "hseId"
    })
    public static class Location {

        @XmlElement(required = true)
        protected Object address;
        @XmlElement(name = "house_number", required = true)
        protected Object houseNumber;
        @XmlElement(required = true)
        protected Object fraction;
        @XmlElement(required = true)
        protected Object direction;
        @XmlElement(name = "street_name", required = true)
        protected Object streetName;
        @XmlElement(required = true)
        protected Object suffix;
        @XmlElement(name = "suffix_dir", required = true)
        protected Object suffixDir;
        @XmlElement(required = true)
        protected Object zipcode;
        @XmlElement(name = "hse_id", required = true)
        protected Object hseId;

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAddress(Object value) {
            this.address = value;
        }

        /**
         * Gets the value of the houseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getHouseNumber() {
            return houseNumber;
        }

        /**
         * Sets the value of the houseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setHouseNumber(Object value) {
            this.houseNumber = value;
        }

        /**
         * Gets the value of the fraction property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getFraction() {
            return fraction;
        }

        /**
         * Sets the value of the fraction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setFraction(Object value) {
            this.fraction = value;
        }

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDirection(Object value) {
            this.direction = value;
        }

        /**
         * Gets the value of the streetName property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getStreetName() {
            return streetName;
        }

        /**
         * Sets the value of the streetName property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setStreetName(Object value) {
            this.streetName = value;
        }

        /**
         * Gets the value of the suffix property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSuffix() {
            return suffix;
        }

        /**
         * Sets the value of the suffix property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSuffix(Object value) {
            this.suffix = value;
        }

        /**
         * Gets the value of the suffixDir property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSuffixDir() {
            return suffixDir;
        }

        /**
         * Sets the value of the suffixDir property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSuffixDir(Object value) {
            this.suffixDir = value;
        }

        /**
         * Gets the value of the zipcode property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getZipcode() {
            return zipcode;
        }

        /**
         * Sets the value of the zipcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setZipcode(Object value) {
            this.zipcode = value;
        }

        /**
         * Gets the value of the hseId property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getHseId() {
            return hseId;
        }

        /**
         * Sets the value of the hseId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setHseId(Object value) {
            this.hseId = value;
        }

    }

}
