//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 02:47:07 PM PST 
//


package com.itafin.boe.geo.response.exactmatch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated.jaxb.gis.addr.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated.jaxb.gis.addr.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressResponse }
     * 
     */
    public AddressResponse createAddressResponse() {
        return new AddressResponse();
    }

    /**
     * Create an instance of {@link AddressResponse.Layers }
     * 
     */
    public AddressResponse.Layers createAddressResponseLayers() {
        return new AddressResponse.Layers();
    }

    /**
     * Create an instance of {@link AddressResponse.Layers.Layer }
     * 
     */
    public AddressResponse.Layers.Layer createAddressResponseLayersLayer() {
        return new AddressResponse.Layers.Layer();
    }

    /**
     * Create an instance of {@link AddressResponse.Layers.Layer.Fields }
     * 
     */
    public AddressResponse.Layers.Layer.Fields createAddressResponseLayersLayerFields() {
        return new AddressResponse.Layers.Layer.Fields();
    }

    /**
     * Create an instance of {@link AddressResponse.Location }
     * 
     */
    public AddressResponse.Location createAddressResponseLocation() {
        return new AddressResponse.Location();
    }

    /**
     * Create an instance of {@link AddressResponse.Coords }
     * 
     */
    public AddressResponse.Coords createAddressResponseCoords() {
        return new AddressResponse.Coords();
    }

    /**
     * Create an instance of {@link AddressResponse.Layers.Layer.Fields.Field }
     * 
     */
    public AddressResponse.Layers.Layer.Fields.Field createAddressResponseLayersLayerFieldsField() {
        return new AddressResponse.Layers.Layer.Fields.Field();
    }

}
